[tool.black]
line-length = 120
skip-string-normalization = true
[tool.isort]
profile = "black"
line_length = 120
[tool.mypy]
python_version = "3.11"
disable_error_code = "import-untyped"
strict = true
exclude = ["tests/"]
[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"